##### DOCKERFILE ######
# Specific Image #
###################

# Inherit from the base image
FROM demo_base_image

# For this specific UseCase : Update APT repositories and install ffmpeg
RUN  apt-get install -y ffmpeg && apt-get clean 

# Expose the port that will be used for networking
EXPOSE 5000

# Command executed when a container is deployed
CMD ["/bin/bash", "start.sh"]

